///////////////////////////////////////////////////////////////////////////////
// MotorControllerInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "MotorControllerServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
