///////////////////////////////////////////////////////////////////////////////
// MotorControllerServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MotorController = 0x3F000000;
#define SRVNAME_MOTORCONTROLLER "MotorController"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MotorControllerCModule1 = {0x81a3d12d,0xd374,0x4588,{0x97,0xa5,0xa5,0x32,0x96,0x5c,0x91,0xdd}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>
